.TH CALENDAR 1
.SH NAME
calendar \- print upcoming events
.SH SYNOPSIS
.B calendar
.RB [ \-d ]
.RB [ \-A
.IR num ]
.RB [ \-B
.IR num ]
.RB [ \-t
.IR [[[ cc ] yy ] mm ] dd ]
.RI [ file... ]
.SH DESCRIPTION
.B calendar
reads the named files for events, one event per line;
and write to standard output those events beginning with either today's date or tomorrow's.
On Fridays and Saturdays, events through Monday are printed.
If a hyphen (\-) is provided as argument,
.B calendar
reads from the standard input.
If no file is provided as argument,
.B calendar
reads the file named
.I calendar
on the current directory or on the directory specified by the CALENDAR_DIR environment variable.
.PP
The options are as follows:
.TP
.BI \-A " num"
Print lines from today and next
.I num
days (forward, future).
.TP
.BI \-B " num"
Print lines from today and previous
.I num
days (backward, past).
.TP
.B \-d
Rather than print the date on the same line of each event,
print the date alone in a line and followed by each event indented with a tab.
.TP
\fB-t\fR[[\fIyyyy\fR]\fImm\fR]dd
Act like the specified value is \(lqtoday\(rq instead of using the current date.
.PP
Each event should begin with a date pattern in the format
.I [[YYYY-[MM]]-DDWW[+N|-N]
or should be the name of a movable fest, such as
.IR easter .
The hyphen (\-) that separates the values can be replaced by a slash (/) or a period (.).
Several date patterns can be supplied separated by a comma (,).
.PP
YYYY should be any year number.
MM should be a month number or a month name (either complete or abbreviate, such as "April" or "Apr").
DD should be the number of a day in the month.
WW should be the name of a day in the week (either complete or abbreviate).
Either DD or WW (or both) must be supplied.
.PP
The date pattern can be followed by +N or -N to specify the week on the month
(for example Sun+2 is the second Sunday in the month, Mon-3 is the third from last Monday in the month).
.SH EXAMPLES
Consider the following input.
.IP
.EX
# holidays
01/01      New Year's day
05/01      Labor Day
07/25      Generic holiday
12/25      Christmas
May/Sun+2  Mother's day
13Fri      Friday the 13th

# classes
Mon,Wed Java Class
Tue,Thu Algebra Class
Tue,Thu Operating Systems Class
Tue,Thu Computer Network Class
.EE
.PP
If today were 09 March 2021, then running
.B calendar
with the options
.B -d
and
.B -A7
on this input would print the following:
.IP
.EX
Sunday     09 May 09
        Mother's day
Monday     10 May 10
        Java Class
Tuesday    11 May 11
        Algebra Class
        Computer Network Class
        Operating Systems Class
Wednesday  12 May 12
        Java Class
Thursday   13 May 13
        Algebra Class
        Computer Network Class
        Operating Systems Class
.EE
.SH SEE ALSO
.IR at (1),
.IR cal (1),
.IR cron (1)
.SH STANDARDS
The
.B calendar
program previously selected lines which had the correct date anywhere in the line.
This is no longer true: the date is only recognized when it occurs at the beginning of a line.
.PP
The
.B calendar
program previously could interpret only one date for each event.
This is no longer true: each event can occur in more than one date
(see the examples for the classes above).
.PP
The
.B calendar
program previously could not read events from the standard input.
This is no longer true: if the argument is a hyphen (\-), events are read from the standard input.
.PP
The
.B calendar
program previously had an option to send a mail to all users.
This is no longer true.
To have your calendar mailed every day, use cron(8).
.SH HISTORY
A
.B calendar
command appeared in Version 7 AT&T UNIX.
